/**
 * V72: User Acquisition Layer - branding constants
 */

export const WATERMARK_DISPLAY = "Generated by ToolEagle – Free AI Creator Tools";
export const COPY_BRANDING = "(Generated by ToolEagle)";

export function textWithCopyBranding(text: string): string {
  const trimmed = text?.trim();
  if (!trimmed) return "";
  return `${trimmed}\n\n${COPY_BRANDING}`;
}
