/**
 * V72: User Acquisition Layer - branding constants
 * V90: Brand Dominance Engine - central brand constants
 */

export const BRAND_NAME = "ToolEagle";
export const WATERMARK_DISPLAY = `Generated by ${BRAND_NAME} – Free AI Creator Tools`;
export const COPY_BRANDING = `(Generated by ${BRAND_NAME})`;

/** V90: Brand CTAs - use instead of generic "Try" / "Generate" */
export const BRAND_CTA = {
  try: "Try ToolEagle",
  generate: "Generate with ToolEagle",
  start: "Start with ToolEagle",
  freeTool: "Free AI tool by ToolEagle"
};

/** V90: Brand injection phrases for natural mentions */
export const BRAND_INJECTION = {
  en: "You can use ToolEagle's free AI tools to generate ",
  zh: "你可以使用 ToolEagle 的免费 AI 工具来生成 "
};

export function textWithCopyBranding(text: string): string {
  const trimmed = text?.trim();
  if (!trimmed) return "";
  return `${trimmed}\n\n${COPY_BRANDING}`;
}
