import { Metadata } from "next";
import Link from "next/link";
import { SiteHeader } from "../_components/SiteHeader";
import { SiteFooter } from "../_components/SiteFooter";
import { createClient } from "@/lib/supabase/server";
import { getRealExamples } from "@/config/seo/content-templates";
import { EXAMPLE_CATEGORIES } from "@/config/example-categories";
import { RelatedLinks } from "@/components/seo/RelatedLinks";
import { ExamplesClient } from "./ExamplesClient";

const BASE_URL = "https://www.tooleagle.com";

export const metadata: Metadata = {
  title: "Creator Examples – Best Captions & Hooks Generated",
  description:
    "Real examples from ToolEagle: best captions, hooks and titles generated by creators. Get inspiration for your next post.",
  alternates: { canonical: `${BASE_URL}/examples` },
  openGraph: {
    title: "Creator Examples | ToolEagle",
    description: "Best captions and hooks generated by creators.",
    url: `${BASE_URL}/examples`
  }
};

export const dynamic = "force-dynamic";

async function getPublicExamples(): Promise<
  { slug: string | null; tool: string; toolSlug: string; prompt: string; result: string; creator: string | null }[]
> {
  try {
    const supabase = await createClient();
    const { data } = await supabase
      .from("public_examples")
      .select("slug, tool_name, tool_slug, input, result, creator_username")
      .order("created_at", { ascending: false })
      .limit(50);

    if (!data?.length) return [];
    return data.map((r) => ({
      slug: r.slug ?? null,
      tool: r.tool_name ?? "",
      toolSlug: r.tool_slug ?? "",
      prompt: r.input ?? "",
      result: r.result ?? "",
      creator: r.creator_username ?? null
    }));
  } catch {
    return [];
  }
}

/** Fallback: curated examples from templates when DB has no public data */
function getCuratedExamples(): { tool: string; prompt: string; result: string; topic: string }[] {
  const topics = ["funny", "fitness", "aesthetic", "gaming", "travel"];
  const results: { tool: string; prompt: string; result: string; topic: string }[] = [];
  for (const topic of topics) {
    const captions = getRealExamples("captions", topic);
    const hooks = getRealExamples("hooks", topic);
    if (captions[0]) {
      results.push({
        tool: "TikTok Caption Generator",
        prompt: `Create ${topic} content for my video`,
        result: captions[0],
        topic
      });
    }
    if (hooks[0]) {
      results.push({
        tool: "Hook Generator",
        prompt: `Hook for ${topic} video`,
        result: hooks[0],
        topic
      });
    }
  }
  return results.slice(0, 12);
}

export default async function ExamplesPage() {
  const publicExamples = await getPublicExamples();
  const curated = getCuratedExamples();
  const hasPublic = publicExamples.length > 0;

  return (
    <main className="min-h-screen bg-white text-slate-900 flex flex-col">
      <SiteHeader />

      <div className="flex-1">
        <section className="bg-slate-50 border-b border-slate-200">
          <div className="container py-12">
            <h1 className="text-3xl sm:text-4xl font-semibold tracking-tight text-slate-900">
              Creator Examples
            </h1>
            <p className="mt-4 text-lg text-slate-600 max-w-2xl">
              Best captions and hooks generated by creators. Get inspiration for your next post.
            </p>
            <div className="mt-6 flex flex-wrap gap-3">
              <Link
                href="/tools"
                className="inline-flex items-center justify-center rounded-xl bg-sky-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-sky-700 transition"
              >
                Generate your own →
              </Link>
              <Link
                href="/creator"
                className="inline-flex items-center justify-center rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50 transition"
              >
                Creator Mode →
              </Link>
            </div>
            <div className="mt-4 flex flex-wrap gap-2">
              {EXAMPLE_CATEGORIES.map((cat) => (
                <Link
                  key={cat.slug}
                  href={`/examples/${cat.slug}`}
                  className="text-sm font-medium text-sky-600 hover:underline"
                >
                  {cat.title} →
                </Link>
              ))}
            </div>
          </div>
        </section>

        <section className="container py-12">
          <h2 className="text-xl font-semibold text-slate-900 mb-6">
            {hasPublic ? "Creator examples" : "Example captions & hooks"}
          </h2>
          <p className="text-sm text-slate-600 mb-6">
            {hasPublic
              ? "Real examples from creators. Get inspiration for your next post."
              : "Curated examples to inspire your next post. Generate your own with our free AI tools."}
          </p>
          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {hasPublic
              ? publicExamples.map((ex, i) => (
                  <ExampleCard
                    key={ex.slug ?? i}
                    slug={ex.slug}
                    tool={ex.tool}
                    toolSlug={ex.toolSlug}
                    prompt={ex.prompt}
                    result={ex.result}
                    creator={ex.creator}
                  />
                ))
              : curated.map((ex, i) => (
                  <ExampleCard
                    key={i}
                    slug={null}
                    tool={ex.tool}
                    toolSlug=""
                    prompt={ex.prompt}
                    result={ex.result}
                    creator={null}
                  />
                ))}
          </div>
        </section>

        <section className="container py-12">
          <RelatedLinks examples={false} />
        </section>

        <section className="container pb-16">
          <div className="rounded-2xl border border-slate-200 bg-slate-50 p-6">
            <h2 className="text-lg font-semibold text-slate-900">Share your examples</h2>
            <p className="mt-2 text-sm text-slate-600">
              After generating, click &quot;Share to Examples&quot; to feature your best captions and hooks here. Requires a creator profile.
            </p>
            <Link
              href="/dashboard/settings"
              className="mt-4 inline-block text-sm font-medium text-sky-600 hover:underline"
            >
              Set up creator profile →
            </Link>
          </div>
        </section>
      </div>

      <SiteFooter />
    </main>
  );
}

function ExampleCard({
  slug,
  tool,
  toolSlug,
  prompt,
  result,
  creator
}: {
  slug: string | null;
  tool: string;
  toolSlug: string;
  prompt: string;
  result: string;
  creator: string | null;
}) {
  const card = (
    <>
      <div className="flex items-center justify-between gap-2 mb-2">
        <span className="text-xs font-medium text-sky-600">{tool}</span>
        {creator && (
          <Link
            href={`/creators/${creator}`}
            className="text-xs text-slate-500 hover:text-sky-600"
            onClick={(e) => slug && e.stopPropagation()}
          >
            @{creator}
          </Link>
        )}
      </div>
      <p className="text-xs text-slate-500 line-clamp-1">Prompt: {prompt}</p>
      <p className="mt-2 text-sm text-slate-800 line-clamp-3">{result}</p>
      <ExamplesClient text={result} />
    </>
  );
  const className = "block rounded-xl border border-slate-200 bg-white p-5 hover:border-slate-300 transition";
  return slug ? (
    <Link href={`/examples/${slug}`} className={className}>
      {card}
    </Link>
  ) : (
    <div className={className}>{card}</div>
  );
}
