import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { BASE_URL } from "@/config/site";

function generateShareable(content: string, toolName: string): string {
  const preview = content.slice(0, 150).replace(/\n/g, " ");
  return `${preview}${content.length > 150 ? "…" : ""}\n\nGenerated by ${toolName} – Free at ${BASE_URL}`;
}

function generateSeoCandidate(content: string, toolName: string): { title: string; description: string } {
  const firstLine = content.split("\n")[0]?.slice(0, 60) || content.slice(0, 60);
  return {
    title: `${firstLine} – ${toolName} Example | ToolEagle`,
    description: `${content.slice(0, 120).replace(/\n/g, " ")}… Generated by ToolEagle ${toolName}. Free AI creator tools.`
  };
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { toolSlug, toolName, content, exampleResult } = body;

    if (!toolSlug || !toolName || !content) {
      return NextResponse.json(
        { error: "Missing toolSlug, toolName, or content" },
        { status: 400 }
      );
    }

    const contentStr = String(content).slice(0, 10000);
    const shareable = generateShareable(contentStr, toolName);
    const seo = generateSeoCandidate(contentStr, toolName);

    const supabase = await createClient();
    const {
      data: { user }
    } = await supabase.auth.getUser();

    const { error } = await supabase.from("ugc_submissions").insert({
      tool_slug: String(toolSlug).slice(0, 100),
      tool_name: String(toolName).slice(0, 200),
      content: contentStr,
      example_result: exampleResult ? String(exampleResult).slice(0, 5000) : null,
      shareable_content: shareable,
      seo_candidate_title: seo.title,
      seo_candidate_description: seo.description,
      user_id: user?.id ?? null
    });

    if (error) {
      console.error("[ugc-submit]", error);
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ ok: true });
  } catch (e) {
    console.error("[ugc-submit]", e);
    return NextResponse.json({ error: "Server error" }, { status: 500 });
  }
}
