import { Metadata } from "next";
import Link from "next/link";
import { decodeResultFromShare } from "@/lib/share";
import { tools } from "@/config/tools";
import { SiteHeader } from "@/app/_components/SiteHeader";
import { SiteFooter } from "@/app/_components/SiteFooter";
import { BASE_URL } from "@/config/site";

type Props = {
  params: Promise<{ id: string }>;
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params;
  const decoded = decodeResultFromShare(id);
  const tool = decoded ? tools.find((t) => t.slug === decoded.toolSlug) : null;
  const contentPreview = decoded?.items?.[0]
    ? decoded.items[0].slice(0, 120).replace(/\n/g, " ") + (decoded.items[0].length > 120 ? "…" : "")
    : "";
  const title = tool ? `${tool.name} – AI Generated Result | ToolEagle` : "Shared Result | ToolEagle";
  const description = contentPreview
    ? `${contentPreview} Generated by ToolEagle – Free AI Creator Tools.`
    : "View AI-generated content shared from ToolEagle. Free TikTok captions, YouTube titles, hooks and more.";

  const url = `${BASE_URL}/share/${id}`;
  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      title,
      description,
      url,
      type: "website",
      siteName: "ToolEagle"
    },
    twitter: {
      card: "summary_large_image",
      title,
      description
    }
  };
}

export default async function SharePage({ params }: Props) {
  const { id } = await params;
  const decoded = decodeResultFromShare(id);
  const tool = decoded ? tools.find((t) => t.slug === decoded.toolSlug) : null;

  if (!decoded || !tool) {
    return (
      <main className="min-h-screen bg-white text-slate-900 flex flex-col">
        <SiteHeader />
        <div className="flex-1 container py-16 text-center">
          <h1 className="text-xl font-semibold text-slate-900">Result not found</h1>
          <p className="mt-2 text-slate-600">This link may be invalid or expired.</p>
          <Link
            href="/tools"
            className="mt-6 inline-block text-sm font-medium text-sky-700 hover:text-sky-800"
          >
            Browse tools →
          </Link>
        </div>
        <SiteFooter />
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-white text-slate-900 flex flex-col">
      <SiteHeader />
      <div className="flex-1 container py-12">
        <div className="max-w-2xl mx-auto">
          <p className="text-xs font-medium text-slate-500 uppercase tracking-wide">
            Shared from {tool.name}
          </p>
          <h1 className="mt-2 text-2xl font-semibold text-slate-900">
            Generated results
          </h1>
          <div className="mt-6 space-y-3">
            {decoded.items.map((text, i) => (
              <div
                key={i}
                className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-800 whitespace-pre-line"
              >
                <span className="text-slate-500 font-medium mr-2">{i + 1}.</span>
                {text}
                <p className="mt-2 text-xs text-slate-500">
                  Generated by ToolEagle – Free AI Creator Tools
                </p>
              </div>
            ))}
          </div>
          <Link
            href={`/tools/${tool.slug}`}
            className="mt-8 inline-flex items-center gap-2 rounded-xl bg-sky-600 px-5 py-3 text-sm font-semibold text-white hover:bg-sky-700 transition"
          >
            Try {tool.name} free →
          </Link>
        </div>
      </div>
      <SiteFooter />
    </main>
  );
}
